@startuml
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

actor "__:FAMILLE__" as famille
participant "__pge:PGE__" as pge

activate famille
famille -> pge ++ : ajouterReservation(idEnfant, idCadeau, quantite)

opt idEnfant, idCadeau, quantite non null ∧ non vide ∧ quantite > 0

  pge -> pge ++ : e=chercherEnfant(idEnfant): Enfant
  return

  pge -> pge ++ : c=chercherCadeau(idCadeau): Cadeau
  return

  opt e != null ∧ c != null

    pge -> pge ++ : stockOK = verifierStock(c, quantite)
    return

    pge -> pge ++ : pointsOK = verifierSolde(e, quantite * c.cout)
    return

    opt stockOK ∧ pointsOK

      pge -> pge ++ : r=chercherReservation(e,c): Reservation
      return

      alt r != null

        pge -> pge ++ : r.incrementerQuantite(quantite)
        return

      else r == null

        create "__r:Reservation__" as r
        pge -> r ++ : r=<<create(e,c,quantite)>>
        return

      end

      pge -> pge ++ : c.decrementerStock(quantite)
      return

      pge -> pge ++ : e.decrementerPoints(quantite * c.cout)
      return

    end
  end
end

return
deactivate famille
@enduml