@startuml
hide empty methods
hide circle
skinparam class {
  BackgroundColor White
  ArrowColor Black
  BorderColor Black
}
skinparam groupInheritance 3

class PGE {
  - nBPointsMaxParEnfant: int
}

class Famille {
  - id: string
  - description: string
}

class Enfant {
  - id: string
  - nom: string
  - prenom: string
  - nbPointsRestants: int
}

class Cadeau {
  - id: string
  - nbStockDisponible: int
  - cout: int
  - description: string
}

class Réservation {
  - id: string
  - quantitee: int
}



PGE --> "*" Famille

@enduml
