@startuml

class Cadeau {
  - id : String
  - nbDisponible : int
  - nbInitial : int
  - cout : int
  - description : String

  + getId() : String
  + getNbDisponible() : int
  + getNbInitial() : int
  + getCout() : int
  + decrementerNbDisponible(quantite : int) : void
  + incrementerNbInitial(quantite : int) : void
  + incrementerNbDisponible(quantite : int) : void
  + verifierReservation() : boolean
  + invariant() : boolean
}

@enduml