@startuml
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

actor "__:SRH__" as srh
participant "__pge:PGE__" as pge
participant "__f:Famille__" as f

activate srh
srh -> pge ++ : ajouterUnEnfant(idFamille, prenom, nom, idEnfant)

opt idFamille, idEnfant, prenom, nom non null ∧ non vide
  pge -> pge ++ : f = chercherFamille(idFamille) : Famille
  return

  opt f != null
    pge -> f ++ : e = chercherEnfant(idEnfant) : Enfant
    return

    opt e == null
      create "__e:Enfant__" as e
      pge -> e ++ : <<create(idEnfant, nom, prenom, nBPointsMaxParEnfant)>>
      return

      pge -> f ++ : ajouterEnfant(e)
      return
    end
  end
end

return
deactivate srh
@enduml