@startuml
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

actor "__:SRH__" as srh
participant "__pge:PGE__" as pge

activate srh
srh -> pge ++ : AjouterEnfant(id, nom, prenom, id_famille)

opt id, nom, prenom, id_famille non null ∧ non vide
  pge -> pge ++ : f = chercherFamille(id_famille) : Famille
  return

  pge -> pge ++ : e = chercherEnfant(id) : Enfant
  return

  opt e == null
    create "__e:Enfant__" as e
    pge -> e ++ : e = <<create(id, nom, prenom)>>
    return

    pge -> pge ++ : ajouterEnfant(f, e)
    return
  end
end

return
deactivate srh
@enduml
