@startuml

EnCréation : entry: constructeur()

Disponible : réservation: ajouterUneReservation()
Disponible : annulation: retirerUneReservation()
Disponible : réassort: effectuerUnReassort()


Épuisé : annulation: retirerUneReservation()
Épuisé : réassort: effectuerUnReassort()


EnDestruction : entry: destructeur()

[*] -right-> EnCréation
EnCréation -right-> Disponible : [nbInitial > 0]
EnCréation -down-> Épuisé : [nbInitial == 0]
Disponible -right-> Épuisé : [nombreDispo == 0]
Épuisé --> Disponible : [nombreDispo > 0]
Disponible -down-> EnDestruction : retrait [aucune réservation : nbInitial == nombreDispo]
Épuisé -down-> EnDestruction : retrait [aucune réservation : nbInitial == nombreDispo]
EnDestruction -left-> [*]

@enduml
