@startuml
hide empty methods
hide circle
skinparam class {
  BackgroundColor White
  ArrowColor Black
  BorderColor Black
}
skinparam groupInheritance 3

class PGE {
  - nBPointsMaxParEnfant: int
  - producteurCE : SubmissionPublisher<String>
}

class Famille {
  - id: String
  - description: String
  - producteur: SubmissionPublisher<String>
  
}

class ConsommateurNotification {
    - id: String
    - souscription: Subscription
}


class Enfant {
  - id: String
  - nom: String
  - prenom: string
  - nbPointsRestants: int
}

class Cadeau {
  - id: String
  - nbDisponible: int
  - nbInitial: int
  - cout: int
  - description: String
}

class Réservation {
  - quantitee: int
}



PGE *--> "*" Famille
PGE *--> "*" Cadeau

Enfant *-->"*" Réservation
Réservation "*"--> "1  " Cadeau


Famille *--> "*" Enfant


@enduml
